### ISSUE TITLE
Explore swapping builder pattern for configuration via maps

### ISSUE THREAD

**Issue by russorat** [ngrok/ngrok-js#37]
it seems configuring objects using maps is more common for javascript than using the builder pattern. let's explore allowing configuration via maps instead and see if that simplifies the API.

**Comment by bobzilladev** [comment]
I've started working on this, will this work as a plan?  https://github.com/ngrok-private/ngrok/issues/17014

**Comment by bobzilladev** [comment]
This was accomplished by these PR's:
https://github.com/ngrok/ngrok-js/pull/42
https://github.com/ngrok/ngrok-js/pull/43
https://github.com/ngrok/ngrok-js/pull/44
